################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
FreeRTOS_Source/croutine.obj: C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/croutine.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/Full_Demo" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib/inc" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/Common/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --display_error_number --diag_warning=225 --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/croutine.pp" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/event_groups.obj: C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/event_groups.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/Full_Demo" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib/inc" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/Common/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --display_error_number --diag_warning=225 --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/event_groups.pp" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/list.obj: C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/list.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/Full_Demo" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib/inc" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/Common/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --display_error_number --diag_warning=225 --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/list.pp" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/queue.obj: C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/queue.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/Full_Demo" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib/inc" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/Common/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --display_error_number --diag_warning=225 --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/queue.pp" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/tasks.obj: C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/tasks.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/Full_Demo" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib/inc" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/Common/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --display_error_number --diag_warning=225 --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/tasks.pp" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/timers.obj: C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/timers.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/Full_Demo" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib/inc" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil/driverlib" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/Common/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/include" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.7/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/Nhut/workspace_v6_1/FreeRTOSV8.2.3/FreeRTOS/Demo/CORTEX_M4F_MSP432_LaunchPad_IAR_CCS_Keil" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --display_error_number --diag_warning=225 --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/timers.pp" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


