before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcurl4-openssl-dev libc-ares-dev libssl-dev libcrypto++-dev zlib1g-dev libsqlite3-dev libfreeimage-dev libreadline-dev
language: cpp
compiler:
  - gcc
script:
  - ./autogen.sh
  - ./configure
  - make clean
  - make
